# Generated by Django 3.1.5 on 2021-01-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.audioclip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='clips',
            field=models.ManyToManyField(related_name='clip_users', through='accounts.UserClip', to='clips.AudioClip'),
        ),
    ]
